# Generated by Django 4.1.3 on 2022-11-23 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('suburb', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postalcode', models.IntegerField()),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('notes1', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('selling_price', models.FloatField()),
                ('prodtype', models.CharField(max_length=100)),
                ('unitsale', models.CharField(max_length=100)),
                ('unitsale2', models.CharField(max_length=100)),
                ('factor_1', models.CharField(max_length=100)),
                ('is_flooring_product', models.BooleanField(default=False)),
                ('m2_price', models.BooleanField(default=False)),
                ('active_field', models.BooleanField(default=False)),
                ('product_image', models.ImageField(upload_to='productimg')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quot_no', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('quot_status', models.CharField(max_length=200)),
                ('market_seg', models.CharField(max_length=200)),
                ('creation_on', models.DateTimeField(auto_now_add=True)),
                ('quot_total', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
