# Generated by Django 4.1.3 on 2022-11-24 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='creation_on',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='quot_total',
        ),
    ]
