# Generated by Django 4.1.3 on 2022-11-24 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_client_delete_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='quot_status',
        ),
    ]
