# Generated by Django 4.1.3 on 2022-12-03 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='quotation_id',
            new_name='quotation',
        ),
        migrations.AddField(
            model_name='section',
            name='product',
            field=models.ManyToManyField(to='app.product'),
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product', models.ManyToManyField(to='app.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.section')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quotation')),
            ],
        ),
    ]
