# Generated by Django 4.1.3 on 2022-12-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_quotation_id_section_quotation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='quot_status',
            field=models.CharField(choices=[('no', 'No Status'), ('scnf', 'Spec Confirmed'), ('act', 'Active'), ('hold', 'On-hold'), ('ocnf', 'Order Confirmed')], default='no', max_length=5),
        ),
    ]
