# Generated by Django 4.1.3 on 2022-12-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_quotation_quot_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='email',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='surname',
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='version',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
