# Generated by Django 4.1.3 on 2022-11-24 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_quotation_item_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='created_by',
            field=models.ForeignKey(default='1-1-2022', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='creation_on',
            field=models.DateTimeField(auto_now_add=True, default='ind'),
            preserve_default=False,
        ),
    ]
