# Generated by Django 4.1.3 on 2022-11-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_quotationitem_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
