# Generated by Django 4.1.3 on 2022-11-28 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_quotation_created_by_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quotation_item',
            new_name='QuotationItem',
        ),
    ]
